### ISSUE TITLE
Is this code base complete? 

### ISSUE THREAD

**Issue by yang1332133** [MIT-TESSE/dsg-rl#2]
Hello , thank you very much for your creative work. I've been reproducing this code recently, but I'm having some problems. Is this code base complete? Is this code base missing DSG related code？

**Comment by ZacRavichandran** [comment]
Hello,

Thank you for you interest in our work.

We have a few projects that are using this functionality. Thus, we've split the codebase into a few repositories. This repo provides the top-level training and evaluation code. Please find the DSG related code in the [tesse-gym](https://github.com/MIT-TESSE/tesse-gym) repo, specifically under the [`tesse_gym.observers.dsg`](https://github.com/MIT-TESSE/tesse-gym/tree/master/src/tesse_gym/observers/dsg) subpackage. Please find the graph neural network code in the [rllib-policies](https://github.com/MIT-TESSE/rllib-policies) repo.
